DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:46: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:55: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
  from .. import h5, h5g, h5i, h5o, h5r, h5t, h5l, h5p, h5s, h5d
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:3: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:68: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:45: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:127: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:99: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling __init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:197: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:112: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:115: __init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:135: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py:738: calling __init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MultiRNNCell.call of <tensorflow.python.ops.rnn_cell_impl.MultiRNNCell object at 0x7fdfe9a6b410>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fdfe9a6bc10>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:178: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:317: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:30: The name tf.nn.rnn_cell.LSTMStateTuple is deprecated. Please use tf.compat.v1.nn.rnn_cell.LSTMStateTuple instead.

WARNING:tensorflow:Entity <bound method ConvLSTMCell.call of <util.cell.ConvLSTMCell object at 0x7fdfe3956a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvLSTMCell.call of <util.cell.ConvLSTMCell object at 0x7fdfe3956a90>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:Entity <bound method ConvLSTMCell.call of <util.cell.ConvLSTMCell object at 0x7fdfe319dfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvLSTMCell.call of <util.cell.ConvLSTMCell object at 0x7fdfe319dfd0>>: AttributeError: 'module' object has no attribute 'Num'
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py:180: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/util/loss.py:47: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:481: The name tf.train.polynomial_decay is deprecated. Please use tf.compat.v1.train.polynomial_decay instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:486: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py:57: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2021-02-04 02:50:26.557446: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-02-04 02:50:26.563773: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-02-04 02:50:30.499428: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5627e815c880 executing computations on platform CUDA. Devices:
2021-02-04 02:50:30.499491: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2021-02-04 02:50:30.499506: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2021-02-04 02:50:30.499516: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (2): GeForce RTX 2080 Ti, Compute Capability 7.5
2021-02-04 02:50:30.499526: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (3): GeForce RTX 2080 Ti, Compute Capability 7.5
2021-02-04 02:50:30.524436: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2021-02-04 02:50:30.524910: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5627e81306f0 executing computations on platform Host. Devices:
2021-02-04 02:50:30.524953: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-02-04 02:50:30.528092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:21:00.0
2021-02-04 02:50:30.530696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:22:00.0
2021-02-04 02:50:30.533271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 2 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:23:00.0
2021-02-04 02:50:30.535466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 3 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:24:00.0
2021-02-04 02:50:30.535860: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2021-02-04 02:50:30.538094: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2021-02-04 02:50:30.539983: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2021-02-04 02:50:30.540477: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2021-02-04 02:50:30.543078: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2021-02-04 02:50:30.544855: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2021-02-04 02:50:30.549307: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-02-04 02:50:30.559122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1, 2, 3
2021-02-04 02:50:30.559166: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2021-02-04 02:50:30.564209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-04 02:50:30.564221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 2 3 
2021-02-04 02:50:30.564232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N N N N 
2021-02-04 02:50:30.564235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   N N N N 
2021-02-04 02:50:30.564239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 2:   N N N N 
2021-02-04 02:50:30.564242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 3:   N N N N 
2021-02-04 02:50:30.569758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10312 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:21:00.0, compute capability: 7.5)
2021-02-04 02:50:30.571490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10312 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:22:00.0, compute capability: 7.5)
2021-02-04 02:50:30.574789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10312 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:23:00.0, compute capability: 7.5)
2021-02-04 02:50:30.578374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10312 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080 Ti, pci bus id: 0000:24:00.0, compute capability: 7.5)
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2021-02-04 02:50:54.067330: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-02-04 02:50:54.785393: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-02-04 02:50:54.942155: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: The graph couldn't be sorted in topological order.
2021-02-04 02:50:56.086627: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] remapper failed: Invalid argument: The graph couldn't be sorted in topological order.
2021-02-04 02:50:56.185770: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2021-02-04 02:50:56.265190: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-02-04 02:50:56.376763: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2021-02-04 02:51:02.356355: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2021-02-04 02:51:02.734507: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-02-05 01:57:46.553262: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:137 : Unknown: /ubc/cs/research/shield/projects/aditya10/RefSeg/ckpts/Gref/3/Gref_iter_400000.tfmodel.data-00000-of-00001.tempstate15114358457352843920; Input/output error
Traceback (most recent call last):
  File "/ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py", line 401, in <module>
    visualize=args.v)
  File "/ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py", line 157, in train
    snapshot_saver.save(sess, snapshot_file % (n_iter + 1))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1173, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: /ubc/cs/research/shield/projects/aditya10/RefSeg/ckpts/Gref/3/Gref_iter_400000.tfmodel.data-00000-of-00001.tempstate15114358457352843920; Input/output error
	 [[node save_1/SaveV2 (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py:58) ]]
  (1) Unknown: /ubc/cs/research/shield/projects/aditya10/RefSeg/ckpts/Gref/3/Gref_iter_400000.tfmodel.data-00000-of-00001.tempstate15114358457352843920; Input/output error
	 [[node save_1/SaveV2 (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py:58) ]]
	 [[save_1/SaveV2/_4016]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node save_1/SaveV2:
 text_objseg/vis_trans_c5_head4/biases (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:445)	
 text_objseg/text_objseg/vis_trans_c5_head4/DW/Adam_1 (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:508)	
 bn4b13_branch2c/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:269)	
 text_objseg/gconv_feat_ln_spa_graph_c3/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:391)	
 text_objseg/vis_trans_c4_head1/DW (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:444)	
 res5c_branch2a/weights (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:99)	
 text_objseg/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/kernel (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:133)	
 text_objseg/gconv_update_ln_spa_graph_c5/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:397)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_2/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:55)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/kernel (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:42)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/W_co (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:62)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_3/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:65)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:53)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_1/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:54)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/W_ci (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:49)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_4/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:66)	
 text_objseg/Variable_1 (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:480)	
 text_objseg/pred_adj/DW (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:428)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/W_cf (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:50)	
 text_objseg/Variable (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:108)

Input Source operations connected to node save_1/SaveV2:
 text_objseg/vis_trans_c5_head4/biases (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:445)	
 text_objseg/text_objseg/vis_trans_c5_head4/DW/Adam_1 (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:508)	
 bn4b13_branch2c/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:269)	
 text_objseg/gconv_feat_ln_spa_graph_c3/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:391)	
 text_objseg/vis_trans_c4_head1/DW (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:444)	
 res5c_branch2a/weights (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/external/tensorflow-deeplab-resnet/kaffe/tensorflow/network.py:99)	
 text_objseg/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/kernel (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:133)	
 text_objseg/gconv_update_ln_spa_graph_c5/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:397)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_2/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:55)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/kernel (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:42)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/W_co (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:62)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_3/gamma (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:65)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:53)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_1/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:54)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/W_ci (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:49)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/LayerNorm_4/beta (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:66)	
 text_objseg/Variable_1 (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:480)	
 text_objseg/pred_adj/DW (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:428)	
 text_objseg/convlstmscope/rnn/conv_lstm_cell/W_cf (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/util/cell.py:50)	
 text_objseg/Variable (defined at ubc/cs/research/shield/projects/aditya10/RefSeg/CMPC_model_graphmod.py:108)

Original stack trace for u'save_1/SaveV2':
  File "ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py", line 401, in <module>
    visualize=args.v)
  File "ubc/cs/research/shield/projects/aditya10/RefSeg/trainval_model.py", line 58, in train
    snapshot_saver = tf.train.Saver(max_to_keep=4)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 505, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 206, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 122, in save_op
    tensors)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1946, in save_v2
    name=name)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

